#!/bin/bash
raw_github_url="https://raw.githubusercontent.com/bob-crutchley/vim/master"
rm -rf ~/.vim
curl $raw_github_url/pathogen | sh 
curl $raw_github_url/plugins | sh 
curl $raw_github_url/.vimrc > ~/.vimrc

