#!/bin/bash
raw_github_url="https://raw.githubusercontent.com/bob-crutchley/vim/rework"
rm -rf ~/.vim
source <(curl -s $raw_github_url/pathogen)
source <(curl -s $raw_github_url/plugins)
curl -s $raw_github_url/.vimrc > ~/.vimrc

