#!/bin/bash
# Polygot
mkdir -p ~/.vim/pack/default/start
git clone https://github.com/sheerun/vim-polyglot ~/.vim/pack/default/start/vim-polyglot
# The NERD Tree
git clone https://github.com/scrooloose/nerdtree ~/.vim/bundle/nerdtree
# vim-gradle
git clone https://github.com/tfnico/vim-gradle ~/.vim/bundle/vim-gradle
# vim-groovy
git clone https://github.com/thecodesmith/vim-groovy ~/.vim/bundle/vim-groovy
# vim-surround
git clone https://github.com/tpope/vim-surround ~/.vim/bundle/vim-surround
# fugitive
git clone https://github.com/tpope/vim-fugitive ~/.vim/bundle/fugitive
# supertab
git clone https://github.com/ervandew/supertab ~/.vim/bundle/supertab
# nerdtree-git-plugin
git clone https://github.com/xuyuanp/nerdtree-git-plugin ~/.vim/bundle/nerdtree-git-plugin 
#vim-airline
git clone https://github.com/vim-airline/vim-airline ~/.vim/bundle/vim-airline

