#!/bin/bash
set -e

echo_green "installing plugins..."

function install_plugins {
	for plugin in "${plugins[@]}"
	do
		author=$(echo $plugin | awk -F\/ '{ print $1 }')
		repo=$(echo $plugin | awk -F\/ '{ print $2 }')
		echo_yellow "$plugin..."
		git clone https://github.com/$author/$repo ~/.vim/bundle/$repo
	done
}

declare -a plugins=(
	sheerun/vim-polyglot
	scrooloose/nerdtree
	tfnico/vim-gradle
	thecodesmith/vim-groovy
	tpope/vim-surround
	tpope/vim-fugitive
	ervandew/supertab
	xuyuanp/nerdtree-git-plugin
	vim-airline/vim-airline
	ekalinin/dockerfile.vim
)

install_plugins
echo_green "done"

